config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  resources :airlines
  resources :airports
  resources :flights
end

app/models/airline.rb
class Airline < ApplicationRecord
end

app/models/airport.rb
class Airport < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flight.rb
class Flight < ApplicationRecord
  has_many :airlines
  has_many :airports
end

app/controllers/airlines_controller.rb
class AirlinesController < ApplicationController

  before_action :set_airline, only: [:update, :edit, :show, :destroy]

  def new
    @airline = Airline.new
  end

  def create
    @airline = Airline.new(airline_params)

    if @airline.save
      redirect_to airlines_path, notice: "Data saved"
    else
      redirect_to request.referrer, flash: {error: @airline.errors.full_messages}
    end
    
  end

  def index
    @airlines = Airline.all
  end

  def update

    if @airline.update(airline_params) 
      redirect_to airlines_path, notice: "Data updated"
    else
      redirect_to request.referrer, flash: {error: @airline.errors.full_messages}
    end
    
  end

  def edit

  end

  def show
  end

  def set_airline
    @airline = Airline.find(params[:id])
  end
  
  def destroy

    airlineId = Flight.where(airline_id: @airline)

    if airlineId.exists?
      redirect_to airports_path, alert: "Cannot delete airport because there is a flight or more related to it. Please change this relation first."
    else
      if @airline.destroy
        redirect_to request.referrer, notice: "The data has been deleted"
      else
        redirect_to request.referrer, flash: {error: @airport.errors.full_messages}
      end
    end

  end
  
  def airline_params
    params.require(:airline).permit(:iata_code, :airline)
  end
  
end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController

  before_action :set_airport, only: [:update, :edit, :show, :destroy]

  def index
    @airports = Airport.all
  end

  def new
    @airport = Airport.new
  end

  def create
    @airport = Airport.new(airport_params)

    if @airport.save
      redirect_to airports_path, notice: "Data saved"
    else
      redirect_to request.referrer, flash: {error: @airport.errors.full_messages} 
    end

  end

  def update
    if @airport.update(airport_params)
      redirect_to airports_path, notice: "Data updated"
    else
      redirect_to request.referrer, flash: {error: @airport.errors.full_messages}
    end
    
  end

  def edit

  end

  def show

  end

  def set_airport
    @airport = Airport.find(params[:id])
  end

  def destroy

    originAirport = Flight.where(origin_airport_id: @airport)
    destinationAirport = Flight.where(destination_airport_id: @airport)

    if originAirport.exists? || destinationAirport.exists?
      redirect_to airports_path, alert: "Cannot delete airport because there is a flight or more related to it. Please change this relation first."
    else
      if @airport.destroy
        redirect_to request.referrer, notice: "The data has been deleted"
      else
        redirect_to request.referrer, flash: {error: @airport.errors.full_messages}
      end
    end
    
  end
  
  private

  def airport_params
    params.require(:airport).permit(:iata_code, :airport, :city, :state, :country, :latitude, :longitude)
  end
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

  before_action :set_flight, only: [:edit, :update, :show, :destroy]
  before_action :set_airlines_and_aiports, only: [:new, :edit, :destroy]

  def index
    @flights = Flight.all
  end
  
  def new
    @flight = Flight.new
  end

  def create
    @flight = Flight.new(flight_params)

    if @flight.save
      redirect_to flights_path, notice: "Data saved"
    else
      redirect_to request.referrer, flash: {error: @flight.errors.full_messages}
    end
    
  end

  def edit
  end

  def update

    if @flight.update(flight_params)
      redirect_to flights_path, notice: "Data updated"
    else
      redirect_to request.referrer, flash: {error: @flight.errors.full_messages}
    end
    
  end

  def show
    @airline = Airline.where(id: @flight.airline_id)
    @origin_airport = Airport.where(id: @flight.origin_airport_id)
    @destination_airport = Airport.where(id: @flight.destination_airport_id)
  end

  def set_flight
    @flight = Flight.find(params[:id])
  end

  def set_airlines_and_aiports
    @airlines = Airline.all
    @airports = Airport.all
  end
  
  def destroy

    if @flight.destroy
      redirect_to flights_path, notice: "The data has been deleted"
    else
      redirect_to request.referrer, flash: { error: @flight.errors.full_messages }
    end
    
  end
  
  private

  def flight_params
    params.require(:flight).permit(:flight_number, :year, :month, :day, :day_of_week, :airline_id, 
      :tail_number, :origin_airport_id, :destination_airport_id, :scheduled_departure, :departure_time,
      :departure_delay, :taxi_out, :wheels_off, :scheduled_time, :elapsed_time, :air_time, :distance,
      :wheels_on, :taxi_in, :scheduled_arrival, :arrival_time, :arrival_delay, :diverted, :cancelled,
      :cancellation_reason, :air_system_delay, :security_delay, :airline_delay, :late_aircraft_delay,
      :weather_delay)
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/airlines_helper.rb
module AirlinesHelper
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/airlines/edit.html.erb
<section>
    <div class="container">
        <div class="row">
            <div class="col text-center">
                <h1>Edit Airline</h1>
            </div>
        </div>

        <div class="row">
            <%= form_for @airline do |airline| %>
                <div class="content">
                    <div class="form-row">
                        <div class="col-12 mb-2">
                            <label class="form-label">Airline Code</label>
                            <%= airline.text_field :iata_code, autofocus: true, autocomplete: false, placeholder: "UA", class: "form-control text-uppercase mb-3" %>
                        
                            <label class="form-label">Airline Name</label>
                            <%= airline.text_field :airline, autocomplete: true, placeholder: "American Airlines", class: "form-control mb-3" %>

                            <%= airline.submit "Update", class: "btn btn-primary" %>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</section>

app/views/airlines/index.html.erb
<section>
    <div class="container">
        <div class="row mx-auto text-align-center mt-5 mb-5">
            <div class="col text-start mt-2">
                <%= link_to "Go to Airports", airports_path, class: "btn btn-success" %>
            </div>
            <div class="col text-center">
                <h1>Airlines List</h1> 
            </div>
            <div class="col text-center mt-2">
                <%= link_to "Create New", new_airline_path, class: "btn btn-primary" %>
            </div>
            <div class="col text-end mt-2">
                <%= link_to "Go to Flights", flights_path, class: "btn btn-success" %>
            </div>
        </div>

        <% if @airlines.blank? %>
            <div class="container">
                <div class="row mx-auto text-align-center mt-10">
                    <p class="fs-3">No data added yet.</p>
                </div>
            </div>
        <% else %>
            <div class="row">
                <div class="col-12">
                    <table>
                        <thead>
                            <tr>
                                <th><p class="fs-5">Airline Name</p></th>
                                <th><p class="fs-5">Actions</p></th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @airlines.each do |a| %>
                                <tr>
                                    <td style="padding-right: 20px;">
                                        <%= link_to airline_path(a), class: "text-decoration-none" do %>
                                            <p class="fs-5"><%= a.airline %></p>
                                        <% end %>
                                    </td>
                                    <td>
                                        <%= link_to "Click to edit", edit_airline_path(a), class: "btn btn-success" %>
                                        <%= link_to "Delete", airline_path(a), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-danger" %>
                                    </td>
                                </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        <% end %>
    </div>
</section>

app/views/airlines/new.html.erb
<section>
    <div class="container">
        <div class="row mb-5 mt-5">
            <div class="col text-center"> 
                <h1>New Airline</h1>
            </div>
        </div>

        <div class="row">
            <%= form_for @airline do |airline| %>
                <div class="content">
                    <div class="form-row">
                        <div class="col-12 mb-2">
                            <label class="form-label">Airline Code</label>
                            <%= airline.text_field :iata_code, autofocus: true, autocomplete: false, placeholder: "UA", class: "form-control text-uppercase mb-3" %>
                        
                            <label class="form-label">Airline Name</label>
                            <%= airline.text_field :airline, autocomplete: true, placeholder: "American Airlines", class: "form-control mb-3" %>

                            <%= airline.submit "Save", class: "btn btn-primary" %>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</section>

app/views/airlines/show.html.erb
<section>
    <div class="container">
        <div class="row">
            <div class="col text-center mt-3">
                <h1>Airline Information</h1>
            </div>
        </div>

        <div class="row">
            <div class="content">
                <div class="form-row">
                    <div class="col-12 mt-2">
                        <strong><p class="fs-4 mb-2">Airline Code</p></strong>
                        <p class="fs-5"><%= @airline.iata_code.upcase() %></p>
                    
                        <strong><p class="fs-4 mb-2">Airline Name</p></strong>
                        <p class="fs-5"><%= @airline.airline %></p>

                        <%= link_to "Go back", airlines_path, class: "btn btn-success" %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/airports/edit.html.erb
<section>
    <div class="container">
        <div class="row mb-5 mt-5">
            <div class="col text-center">
                <h1>Edit Airport</h1>
            </div>
        </div>

        <div class="row">
            <%= form_for @airport do |airport| %>
                <div class="content">
                    <div class="form-row">
                        <div class="col-12 mb-2">
                            <label class="form-label">Airport Code</label>
                            <%= airport.text_field :iata_code, autofocus: true, autocomplete: false, placeholder: "ABE", class: "form-control text-uppercase mb-3" %>
                        
                            <label class="form-label">Airport Name</label>
                            <%= airport.text_field :airport, autocomplete: true, placeholder: "Alburquerque International Sunport", class: "form-control mb-3" %>

                            <label class="form-label">City</label>
                            <%= airport.text_field :city, autocomplete: true, placeholder: "Alburquerque", class: "form-control mb-3" %>

                            <label class="form-label">State</label>
                            <%= airport.text_field :state, autocomplete: true, placeholder: "NM", class: "form-control text-uppercase mb-3" %>

                            <label class="form-label">Country</label>
                            <%= airport.text_field :country, autocomplete: true, placeholder: "USA", class: "form-control text-uppercase mb-3" %>

                            <label class="form-label">Latitude</label>
                            <%= airport.text_field :latitude, autocomplete: true, placeholder: "35.04022", class: "form-control mb-3" %>

                            <label class="form-label">Longitude</label>
                            <%= airport.text_field :longitude, autocomplete: true, placeholder: "-106.60919", class: "form-control mb-3" %>

                            <%= airport.submit "Update", class: "btn btn-primary" %>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</section>

app/views/airports/index.html.erb
<section>
    <div class="container">
        <div class="row mx-auto text-align-center mt-5 mb-5">
            <div class="col text-start mt-2">
                <%= link_to "Go Home", root_path, class: "btn btn-success" %>
            </div>
            <div class="col text-center">
                <h1>Airports List</h1>
            </div>
            <div class="col text-center mt-2">
                <%= link_to "Create New", new_airport_path, class: "btn btn-primary" %>
            </div>
            <div class="col text-end mt-2">
                <%= link_to "Go to Airlines", airlines_path, class: "btn btn-success" %>
            </div>
        </div>

        <% if @airports.blank? %>
            <div class="container">
                <div class="row mx-auto text-align-center mt-10">
                    <p class="fs-3">No data added yet.</p>
                </div>
            </div>
        <% else %>
            <div class="row">
                <div class="col-12">
                    <table>
                        <thead>
                            <tr>
                                <th><p class="fs-5">Airport Name</p></th>
                                <th><p class="fs-5">Actions</p></th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @airports.each do |a| %>
                                <tr>
                                    <td style="padding-right: 20px;">
                                        <%= link_to airport_path(a), class: "text-decoration-none" do %>
                                            <p class="fs-5"><%= a.airport %></p>
                                        <% end %>
                                    </td>
                                    <td>
                                        <%= link_to "Click to edit", edit_airport_path(a), class: "btn btn-success" %>
                                        <%= link_to "Delete", airport_path(a), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-danger" %>
                                    </td>
                                </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        <% end %>
    </div>
</section>

app/views/airports/new.html.erb
<section>
    <div class="container">
        <div class="row mb-5 mt-5">
            <div class="col text-center">
                <h1>New Airport</h1>
            </div>
        </div>

        <div class="row">
            <%= form_for @airport do |airport| %>
                <div class="content">
                    <div class="form-row">
                        <div class="col-12 mb-2">
                            <label class="form-label">Airport Code</label>
                            <%= airport.text_field :iata_code, autofocus: true, autocomplete: false, placeholder: "ABE", class: "form-control text-uppercase mb-3" %>
                        
                            <label class="form-label">Airport Name</label>
                            <%= airport.text_field :airport, autocomplete: true, placeholder: "Alburquerque International Sunport", class: "form-control mb-3" %>

                            <label class="form-label">City</label>
                            <%= airport.text_field :city, autocomplete: true, placeholder: "Alburquerque", class: "form-control mb-3" %>

                            <label class="form-label">State</label>
                            <%= airport.text_field :state, autocomplete: true, placeholder: "NM", class: "form-control text-uppercase mb-3" %>

                            <label class="form-label">Country</label>
                            <%= airport.text_field :country, autocomplete: true, placeholder: "USA", class: "form-control text-uppercase mb-3" %>

                            <label class="form-label">Latitude</label>
                            <%= airport.text_field :latitude, autocomplete: true, placeholder: "35.04022", class: "form-control mb-3" %>

                            <label class="form-label">Longitude</label>
                            <%= airport.text_field :longitude, autocomplete: true, placeholder: "-106.60919", class: "form-control mb-3" %>

                            <%= airport.submit "Save", class: "btn btn-primary" %>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</section>

app/views/airports/show.html.erb
<section>
    <div class="container">
        <div class="row mb-5 mt-5">
            <div class="col text-center mt-3">
                <h1>Airport Information</h1>
            </div>
        </div>

        <div class="content">
            <div class="row">
                <div class="col-12 mt-2">
                    <strong><p class="fs-4 mb-2">Airport Code</p></strong>
                    <p class="fs-5"><%= @airport.iata_code.upcase() %></p>
                
                    <strong><p class="fs-4 mb-2">Airport Name</p></strong>
                    <p class="fs-5"><%= @airport.airport %></p>

                    <strong><p class="fs-4 mb-2">City</p></strong>
                    <p class="fs-5"><%= @airport.city %></p>

                    <strong><p class="fs-4 mb-2">State</p></strong>
                    <p class="fs-5"><%= @airport.state.upcase() %></p>

                    <strong><p class="fs-4 mb-2">Country</p></strong>
                    <p class="fs-5"><%= @airport.country.upcase() %></p>

                    <strong><p class="fs-4 mb-2">Latitude</p></strong>
                    <p class="fs-5"><%= @airport.latitude %></p>

                    <strong><p class="fs-4 mb-2">Longitude</p></strong>
                    <p class="fs-5"><%= @airport.longitude %></p>

                    <%= link_to "Go back", airports_path, class: "btn btn-success mb-5" %>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/flights/index.html.erb
<section>
    <div class="container">
        <div class="row mx-auto text-align-center mt-5 mb-5">
            <div class="col text-start mt-2">
                <%= link_to "Go to Airlines", airlines_path, class: "btn btn-success" %>
            </div>
            <div class="col text-center">
                <h1>Flights List</h1>
            </div>
            <div class="col text-center mt-2">
                <%= link_to "Create New", new_flight_path, class: "btn btn-primary" %>
            </div>
            <div class="col text-end mt-2">
                <%= link_to "Go Home", root_path, class: "btn btn-success" %>
            </div>
        </div>

        <% if @flights.blank? %>
            <div class="container">
                <div class="row mx-auto text-align-center mt-10">
                    <p class="fs-3">No data added yet.</p>
                </div>
            </div>
        <% else %>
            <div class="row">
                <div class="col-12">
                    <table>
                        <thead>
                            <tr>
                                <th><p class="fs-5">Flight Number</p></th>
                                <th><p class="fs-5">Actions</p></th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @flights.each do |f| %>
                                <tr>
                                    <td style="padding-right: 20px;">
                                        <%= link_to flight_path(f), class: "text-decoration-none" do %>
                                            <p class="fs-5">Flight No. <%= f.flight_number %></p>
                                        <% end %>
                                    </td>
                                    <td>
                                        <%= link_to "Click to edit", edit_flight_path(f), class: "btn btn-success" %>
                                        <%= link_to "Delete", flight_path(f), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-danger" %>
                                    </td>
                                </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        <% end %>
    </div>
</section>

app/views/flights/new.html.erb
<section>
    <div class="container">
        <div class="row mb-5 mt-5">
            <div class="col text-center">
                <h1>New Flight</h1>
            </div>
        </div>

        <div class="row">
            <%= form_for @flight do |flight| %>
                <div class="content">
                    <div class="row">
                        <div class="col-4 mb-2">
                            <label class="form-label">Flight Number</label>
                            <%= flight.text_field :flight_number, autofocus: true, autocomplete: false, placeholder: "98", class: "form-control mb-3" %>
                        </div>
                        <div class="col-4 mb-2">
                            <label class="form-label">Year</label>
                            <%= flight.text_field :year, autocomplete: true, placeholder: "2015", class: "form-control mb-3" %>
                        </div>
                        <div class="col-4 mb-2">
                            <label class="form-label">Month</label>
                            <%= flight.text_field :month, autocomplete: true, placeholder: "1", class: "form-control mb-3" %>
                        </div>
                        
                        <div class="col-4 mb-2">
                            <label class="form-label">Day</label>
                            <%= flight.text_field :day, autocomplete: true, placeholder: "1", class: "form-control mb-3" %>
                        </div>

                        <div class="col-4 mb-2">
                            <label class="form-label">Day of Week</label>
                            <%= flight.text_field :day_of_week, autocomplete: true, placeholder: "4", class: "form-control mb-3" %>
                        </div>

                        <div class="col-4 mb-2">
                            <label class="form-label">Airline</label>
                            <%= flight.select(:airline_id, options_for_select(@airlines.map{ |a| [a.iata_code, a.id] }), {}, {class: "form-select mb-3"}) %>
                        </div>

                        <div class="col-4 mb-2">
                            <label class="form-label">Tail Number</label>
                            <%= flight.text_field :tail_number, autocomplete: true, placeholder: "N407AS", class: "form-control text-uppercase mb-3" %>
                        </div>

                        <div class="col-4 mb-2">
                            <label class="form-label">Origin Airport</label>
                            <%= flight.select(:origin_airport_id, options_for_select(@airports.map{ |a| [a.iata_code, a.id] }), {}, {class: "form-select mb-3"}) %>
                        </div>

                        <div class="col-4 mb-2">
                            <label class="form-label">Destination Airport</label>
                            <%= flight.select(:destination_airport_id, options_for_select(@airports.map{ |a| [a.iata_code, a.id] }), {}, {class: "form-select mb-3"}) %>
                        </div>

                        <div class="col-4 mb-2">
                            <label class="form-label">Scheduled Departure</label>
                            <%= flight.text_field :scheduled_departure, autocomplete: true, placeholder: "0005", class: "form-control mb-3" %>
                        </div>

                        <div class="col-4 mb-2">
                            <label class="form-label">Departure Time</label>
                            <%= flight.text_field :departure_time, autocomplete: true, placeholder: "2354", class: "form-control mb-3" %>
                        </div>

                        <div class="col-4 mb-2">
                            <label class="form-label">Departure Delay</label>
                            <%= flight.text_field :departure_delay, autocomplete: true, placeholder: "-11", class: "form-control mb-3" %>
                        </div>

                        <div class="col-4 mb-2">
                            <label class="form-label">Taxi Out</label>
                            <%= flight.text_field :taxi_out, autocomplete: true, placeholder: "21", class: "form-control mb-3" %>
                        </div>

                        <div class="col-4 mb-2">
                            <label class="form-label">Wheels Off</label>
                            <%= flight.text_field :wheels_off, autocomplete: true, placeholder: "0015", class: "form-control mb-3" %>
                        </div>

                        <div class="col-4 mb-2">
                            <label class="form-label">Scheduled Time</label>
                            <%= flight.text_field :scheduled_time, autocomplete: true, placeholder: "205", class: "form-control mb-3" %>
                        </div>

                        <div class="col-4 mb-2">
                            <label class="form-label">Elapsed Time</label>
                            <%= flight.text_field :elapsed_time, autocomplete: true, placeholder: "194", class: "form-control mb-3" %>
                        </div>

                        <div class="col-4 mb-2">
                            <label class="form-label">Air Time</label>
                            <%= flight.text_field :air_time, autocomplete: true, placeholder: "169", class: "form-control mb-3" %>
                        </div>

                        <div class="col-4 mb-2">
                            <label class="form-label">Distance</label>
                            <%= flight.text_field :distance, autocomplete: true, placeholder: "1448", class: "form-control mb-3" %>
                        </div>

                        <div class="col-4 mb-2">
                            <label class="form-label">Wheels On</label>
                            <%= flight.text_field :wheels_on, autocomplete: true, placeholder: "0404", class: "form-control mb-3" %>
                        </div>

                        <div class="col-4 mb-2">
                            <label class="form-label">Taxi In</label>
                            <%= flight.text_field :taxi_in, autocomplete: true, placeholder: "4", class: "form-control mb-3" %>
                        </div>

                        <div class="col-4 mb-2">
                            <label class="form-label">Scheduled Arrival</label>
                            <%= flight.text_field :scheduled_arrival, autocomplete: true, placeholder: "0430", class: "form-control mb-3" %>
                        </div>

                        <div class="col-4 mb-2">
                            <label class="form-label">Arrival Time</label>
                            <%= flight.text_field :arrival_time, autocomplete: true, placeholder: "0408", class: "form-control mb-3" %>
                        </div>

                        <div class="col-4 mb-2">
                            <label class="form-label">Arrival Delay</label>
                            <%= flight.text_field :arrival_delay, autocomplete: true, placeholder: "-22", class: "form-control mb-3" %>
                        </div>

                        <div class="col-4 mb-2">
                            <label class="form-label">Diverted</label>
                            <%= flight.text_field :diverted, autocomplete: true, placeholder: "0", class: "form-control mb-3" %>
                        </div>

                        <div class="col-4 mb-2">
                            <label class="form-label">Cancelled</label>
                            <%= flight.text_field :cancelled, autocomplete: true, placeholder: "0", class: "form-control mb-3" %>
                        </div>

                        <div class="col-4 mb-2">
                            <label class="form-label">Cancellation Reason</label>
                            <%= flight.text_area :cancellation_reason, autocomplete: true, placeholder: "Couldn't travel", class: "form-control mb-3" %>
                        </div>

                        <div class="col-4 mb-2">
                            <label class="form-label">Air System Delay</label>
                            <%= flight.text_field :air_system_delay, autocomplete: true, placeholder: "0", class: "form-control mb-3" %>
                        </div>

                        <div class="col-4 mb-2">
                            <label class="form-label">Security Delay</label>
                            <%= flight.text_field :security_delay, autocomplete: true, placeholder: "0", class: "form-control mb-3" %>
                        </div>

                        <div class="col-4 mb-2">
                            <label class="form-label">Airline Delay</label>
                            <%= flight.text_field :airline_delay, autocomplete: true, placeholder: "0", class: "form-control mb-3" %>
                        </div>

                        <div class="col-4 mb-2">
                            <label class="form-label">Late Aircraft Delay</label>
                            <%= flight.text_field :late_aircraft_delay, autocomplete: true, placeholder: "0", class: "form-control mb-3" %>
                        </div>

                        <div class="col-4 mb-2">
                            <label class="form-label">Weather Delay</label>
                            <%= flight.text_field :weather_delay, autocomplete: true, placeholder: "0", class: "form-control mb-3" %>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6 mb-5">
                            <%= flight.submit "Save", class: "btn btn-primary" %>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</section>